services:
  frontend:
    build:
      context: .
      target: frontend
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    image: dnd-combat-tracker-frontend:${APP_VERSION:-dev}
    container_name: dnd-combat-tracker-frontend
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - proxy
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dnd-frontend.rule=Host(`dnd.delusionalreality.com`)"
      - "traefik.http.routers.dnd-frontend.entrypoints=websecure"
      - "traefik.http.routers.dnd-frontend.tls.certresolver=cloudflare"
      - "traefik.http.services.dnd-frontend.loadbalancer.server.port=80"

  api:
    build:
      context: .
      target: api
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    image: dnd-combat-tracker-api:${APP_VERSION:-dev}
    container_name: dnd-combat-tracker-api
    restart: unless-stopped
    environment:
      PORT: 4000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-change-me}
    volumes:
      - ./data:/app/data
    networks:
      - app

networks:
  proxy:
    external: true
  app:
    internal: true
